site_name: MkDocs Mermaid to Image Plugin
site_url: https://nuitsjp.github.io/mkdocs-mermaid-to-image/
repo_url: https://github.com/nuitsjp/mkdocs-mermaid-to-image

theme:
  name: material
  language: ja

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

plugins:
  - search
  - mermaid-to-image:
      enabled: true
      output_dir: assets/images
      image_format: png
      mermaid_config: assets/mermaid_config.json
      mmdc_path: mmdc
      theme: default
      background_color: white
      width: 800
      height: 600
      scale: 1.0
      css_file: assets/mermaid.css
      puppeteer_config: assets/puppeteer_config.json
      temp_dir: assets/temp
      cache_enabled: true
      cache_dir: .mermaid_cache
      preserve_original: false
      error_on_fail: false
      log_level: INFO

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.highlight
  - toc:
      permalink: true
