name: Publish to PyPI

on:
  workflow_dispatch:

jobs:
  # CIワークフローを先に実行
  ci:
    uses: ./.github/workflows/ci.yml

  # CI失敗時の通知ジョブ
  ci-failure:
    needs: ci
    if: ${{ needs.ci.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: CI Failed
        run: |
          echo "::error::CI workflow failed. Publication cancelled."
          echo "Please fix the CI issues before attempting to publish."
          exit 1

  publish:
    needs: ci
    if: ${{ needs.ci.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
